#!/bin/sh
# -*- coding: utf-8-unix -*-
# vim:fileencoding=utf-8:ff=unix
# @(#) Tiny File Transmit SeRVice/SeRVer (one-time).

# Copyright (c) 2014 eel3
#
# This software is provided 'as-is', without any express or implied
# warranty. In no event will the authors be held liable for any damages
# arising from the use of this software.
#
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:
#
#     1. The origin of this software must not be misrepresented; you must not
#     claim that you wrote the original software. If you use this software
#     in a product, an acknowledgment in the product documentation would be
#     appreciated but is not required.
#
#     2. Altered source versions must be plainly marked as such, and must not be
#     misrepresented as being the original software.
#
#     3. This notice may not be removed or altered from any source
#     distribution.

set -u
umask 0022
IFS=$(printf ' \t\n_'); IFS=${IFS%_}
PATH=/bin:/usr/bin:/usr/local/bin
export IFS LC_ALL=C LANG=C PATH

readonly progname="${0##*/}"
readonly version=1.1.1.20220710

# this server application name.
readonly appname="tftsrv/1.1.1"

# There are several implementations named `netcat', and they have different options.
#
# For traditional netcat (Debian GNU/Linux 5.0):
# readonly nccmd="nc -l -q 0 -p"
#
# For OpenBSD netcat (Ubuntu 10.04):
readonly nccmd="nc -l"

# echo command for HTTP request/response.
#
# Usually use:
# readonly httpecho="echo -n -e"
#
# In Ubuntu 10.04 (bash 4.1.5), echo can't interpret `-e' option:
readonly httpecho="echo -n"
#
# In Mac OS X 10.8
# readonly httpecho=printf

# Default parameters.
# If no file name or file name is `-',
# we don't output Content-Length and translate data from stdin.
readonly defport=5432
readonly deffile='-'

# error <message>
error() {
    echo "$progname:" ${@+"$@"} 1>&2
    exit 1
}

# usage <output> <exit-code>
usage() {
    cat <<- EOT >"$1"
		$appname - Tiny File Transmit SeRVice/SeRVer (fake httpd)
		usage: $progname [-hv] [-p port] [-f file]
		option:
		    -f  Translation file (or stdin)
		    -h  Show this help message and exit
		    -p  Listen port (usually not needed). Default is $defport
		    -v  Show program's version number and exit
	EOT
    exit "$2"
}

# version (no parameter)
version() {
    echo "$progname $version" 1>&2
    exit 0
}

# parse options
port=$defport
file=$deffile

opt=
while getopts 'f:hp:v' opt; do
    case $opt in
    f)      file=$OPTARG
            [ "$file" = '-' ] || [ -f "$file" ] || error "$file: Invalid argument"
            ;;
    h)      usage /dev/stdout 0
            ;;
    p)      port=$OPTARG
            ;;
    v)      version
            ;;
    \?)     usage /dev/stderr 1
            ;;
    esac
done
shift $((OPTIND - 1))

[ $# -eq 0 ] || usage /dev/stderr 1

# exec one-time dummy HTTP service
{
    $httpecho "HTTP/1.0 200 OK\r\n"
    $httpecho "Date: $(date -u '+%a, %d %b %Y %T GMT')\r\n"
    $httpecho "Server: $appname\r\n"
    [ "$file" != '-' ] && $httpecho "Content-Length: $(wc -c <"$file" | sed 's/[ \t]*//g')\r\n"
    $httpecho "Content-Type: application/octet-stream\r\n"
    $httpecho "Connection: close\r\n"
    $httpecho "\r\n"
    cat "$file"
} | $nccmd "$port"
